docker_wrapper: bug fixes, and failed attempt at checkpoint/restart
Fixed bug in detection of container state at startup.
If container is paused, unpause it rather than restarting.

(Unix) catch quit signals (INT, QUIT, TERM, TSTP) and pause container.
It now works correctly if you ctrl-C the client.

Checkpoint/restart:
    Podman has checkpoint/restore commands, using the CRIU library.
    Docker has analogous but different commands.

    I added code to the wrapper to periodically checkpoint,
    and (on startup) to restore a checkpoint if present.
    But I was unable to get this to work.

    In fact I couldn't get the underlying Podman commands to work.
    If I checkpoint a container, run it some more, stop it, then restore,
    I always get the unhelpful error message
    Error: OCI runtime error: runc: criu failed: type RESTORE errno 0
    (Note to self: make sure the Podman features work
    before changing the wrapper).

    So I gave up.  But that's OK: the only use case is when the
    computer is rebooted, which is rare.
    On other cases (e.g. exiting the client),
    we pause/unpause, and no work is lost.

    I left the code in the wrapper, commented out,
    in case we figure out the Podman issue.

also: fix warning msgs in the BUDA web interface