Manager Mac: fix missing include
Build on Travis is failing with:
In file included from /Users/travis/build/BOINC/boinc/clientgui/DlgOptions.cpp:34:
../clientgui/BOINCDialupManager.h:49:5: error: unknown type name 'wxDialUpManager'
Which is strange since DlgOptions.cpp already includes stdwx.h which includes wx/dialup.h